[package]
name = "system_obslugi_studentow"
version = "0.1.0"
authors = ["DzimiX <dzimixpl@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
